---
- name: Install
  become: yes  # pour passer l'utilisateur en mode root
  apt: name= nginx state= latest # il va récupérrer la dernière vesrion de nginx

- name: Start
  become: yes
  service: name=nginx state=started  enabled= true # enabled = true vuet dire lance le service dès que le système d'exxploitation démarre

- name: unlook the default.conf
  become: yes
  file: path =/etc/nginx /sites-eanbled/default state = absent
  notify: nginx reload


- name: Création du dossier
  become: yes
  file: path =/home/{{ user }}/{{ domain }} state=directory owner={{ user }}

- name: Liens  vers www
  become: yes
  file: src=/home/{{ user }}/{{ domain }} dest=/var/www/{{ domain }} state=link

- name: Création de la configuration nginx
 become: yes
 template: src=template/nginx.j2 dest=/etc/nginx/sites-availables/{{ domain }} update=yes

- name: Activation du domaine {{ domain }}
  become: yes
  file: src=/etc/nginx/sites-available/ {{ domain }} dest=/etc/nginx/sites-enabes/{{ domain }} state= link
  notify: nginx reload
 


...